scoreboard objectives add points dummy
scoreboard objectives add score dummy
scoreboard objectives add claimblocks dummy
scoreboard objectives add minutes dummy
scoreboard objectives add hours dummy
scoreboard objectives add level dummy
scoreboard objectives add tier dummy
scoreboard objectives add random dummy
scoreboard objectives add quests dummy
scoreboard objectives add newplayers dummy
scoreboard objectives add alive dummy
scoreboard objectives add deaths dummy
scoreboard objectives add kills dummy
scoreboard objectives add sound dummy
scoreboard objectives add action dummy
scoreboard objectives add warns dummy
scoreboard objectives add trail1 dummy
scoreboard objectives add trail2 dummy
scoreboard objectives add trail3 dummy
scoreboard objectives add trail4 dummy
scoreboard objectives add trail5 dummy
scoreboard objectives add trail6 dummy
scoreboard objectives add trail7 dummy
scoreboard objectives add trail8 dummy
scoreboard objectives add trail9 dummy
scoreboard objectives add trail10 dummy
scoreboard objectives add kit1 dummy
scoreboard objectives add kit2 dummy
scoreboard objectives add kit3 dummy
scoreboard objectives add kit4 dummy
scoreboard objectives add kit5 dummy
scoreboard objectives add peffect1 dummy
scoreboard objectives add peffect2 dummy
scoreboard objectives add peffect3 dummy
scoreboard objectives add peffect4 dummy
scoreboard objectives add peffect5 dummy
scoreboard objectives add peffect6 dummy
scoreboard objectives add peffect7 dummy
scoreboard objectives add peffect8 dummy
scoreboard objectives add rank1 dummy
scoreboard objectives add rank2 dummy
scoreboard objectives add rank3 dummy