scoreboard players operation "Rocked isabotrn" displaypoints = "Rocked isabotrn" points
effect @a[tag=bot] invisibility 11 255 true
effect @a[tag=bot] resistance 11 255 true
effect @a[tag=bot] fire_resistance 11 255 true
clear @a[tag=bot]
scoreboard players reset @a[tag=bot] points
scoreboard players reset @a[tag=bot] minutes
scoreboard players reset @a[tag=bot] hours
tag @a[tag=bot] remove Valid
