tag @a[scores={hours=1}, tag=!p1] add p1
tag @a[scores={hours=5}, tag=!p2] add p2
tag @a[scores={hours=10}, tag=!p3] add p3
tag @a[scores={hours=15}, tag=!p4] add p4
tag @a[scores={hours=20}, tag=!p5] add p5
tag @a[scores={hours=30}, tag=!p6] add p6
tag @a[scores={hours=40}, tag=!p7] add p7
tag @a[scores={hours=50}, tag=!p8] add p8
tag @a[scores={hours=75}, tag=!p9] add p9
tag @a[scores={hours=100}, tag=!p10] add p10